package dev.slne.surf.skill.core.paper.util

import com.github.benmanes.caffeine.cache.Caffeine
import com.sksamuel.aedile.core.expireAfterWrite
import dev.slne.surf.api.paper.pdc.block.pdc
import dev.slne.surf.skill.api.paper.Skill
import dev.slne.surf.skill.api.paper.SkillInstance
import dev.slne.surf.skill.api.paper.player.incrementExperience
import dev.slne.surf.skill.api.paper.player.skillPlayer
import org.bukkit.Material
import org.bukkit.NamespacedKey
import org.bukkit.block.Block
import org.bukkit.block.BlockType
import org.bukkit.event.block.*
import org.bukkit.event.world.StructureGrowEvent
import org.bukkit.inventory.ItemType
import org.bukkit.persistence.PersistentDataType
import java.util.*
import kotlin.time.Duration.Companion.seconds

object BlockExperienceHandler {
    private val MODIFIED_BLOCK_KEY = NamespacedKey("surf", "skill_modified_block")

    val blockBreakCache = Caffeine.newBuilder()
        .maximumSize(10_000)
        .expireAfterWrite(10.seconds)
        .build<BlockBreakEvent, Boolean>()

    fun handleBlockPlace(event: BlockPlaceEvent) {
        event.block.setUneligibleForExperience()
    }

    fun handleBlockBreak(event: BlockBreakEvent) {
        val block = event.block

        blockBreakCache.put(event, block.isEligibleForExperience())
        block.setEligibleForExperience()
    }

    fun handleStructureGrow(event: StructureGrowEvent) {
        // Important:
        // A player-placed sapling is replaced by the first log.
        // The sapling's location must become eligible again because the new log
        // was naturally generated by growth, not directly placed by the player.
        event.location.block.setEligibleForExperience()

        for (state in event.blocks) {
            state.block.setEligibleForExperience()
        }
    }

    fun handleBlockFertilize(event: BlockFertilizeEvent) {
        // Bonemeal growth can replace the original fertilized block.
        // Clear the skill-specific modified flag from both the origin and all
        // resulting changed blocks.
        event.block.setEligibleForExperience()

        for (state in event.blocks) {
            state.block.setEligibleForExperience()
        }
    }

    fun handleBlockGrow(event: BlockGrowEvent) {
        // Generic single-block growth/replacement fallback.
        // Only clear when the material actually changes. Age changes of crops
        // should not automatically rewrite skill provenance here.
        if (event.newState.type != event.block.type) {
            event.block.setEligibleForExperience()
        }
    }

    inline fun <reified S : Skill> handleBlockDropItem(
        event: BlockDropItemEvent,
        experienceFunction: (ItemType, BlockType) -> Int
    ) {
        val (_, eligible) = findCacheByBlock(event.block) ?: return
        if (!eligible) return

        val totalExperience = event.items.mapNotNull {
            val blockType = event.blockState.type.asBlockType() ?: return@mapNotNull null
            val itemType = it.itemStack.type.asItemType() ?: return@mapNotNull null

            experienceFunction(itemType, blockType)
        }.sum()

        if (totalExperience <= 0) return

        SkillInstance.launch {
            event.player.skillPlayer().incrementExperience<S>(totalExperience)
        }
    }

    fun findCacheByBlock(block: Block) = blockBreakCache.asMap()
        .entries
        .firstOrNull { it.key.block.location == block.location }

    private val ORES = EnumSet.of(
        Material.COAL_ORE,
        Material.DEEPSLATE_COAL_ORE,
        Material.IRON_ORE,
        Material.DEEPSLATE_IRON_ORE,
        Material.COPPER_ORE,
        Material.DEEPSLATE_COPPER_ORE,
        Material.GOLD_ORE,
        Material.DEEPSLATE_GOLD_ORE,
        Material.REDSTONE_ORE,
        Material.DEEPSLATE_REDSTONE_ORE,
        Material.LAPIS_ORE,
        Material.DEEPSLATE_LAPIS_ORE,
        Material.DIAMOND_ORE,
        Material.DEEPSLATE_DIAMOND_ORE,
        Material.EMERALD_ORE,
        Material.DEEPSLATE_EMERALD_ORE,
        Material.NETHER_QUARTZ_ORE,
        Material.NETHER_GOLD_ORE,
        Material.ANCIENT_DEBRIS
    )

    fun isEligibleForExperience(block: Block) =
        block.type in ORES || !block.pdc().has(MODIFIED_BLOCK_KEY)

    fun setEligibleForExperience(block: Block) {
        block.pdc().remove(MODIFIED_BLOCK_KEY)
    }

    fun setUneligibleForExperience(block: Block) {
        block.pdc().set(MODIFIED_BLOCK_KEY, PersistentDataType.BOOLEAN, true)
    }
}

fun Block.isEligibleForExperience() = BlockExperienceHandler.isEligibleForExperience(this)
fun Block.setEligibleForExperience() = BlockExperienceHandler.setEligibleForExperience(this)
fun Block.setUneligibleForExperience() = BlockExperienceHandler.setUneligibleForExperience(this)